### PR TITLE
feat: support multiple arguments in the command line

### PR DESCRIPTION
**Pull request by vanpipy**
For closing #144

### CODE REVIEW

**Comment by jaywcjlove** [comment]
@vanpipy Is gadget `minimist` more appropriate?

**Comment by vanpipy** [comment]
Hi @jaywcjlove , i got your idea. Because of the future of the mocker commander, try to replace the `minimist` of the `commander`. If we want to enhance the mocker commander, it will be easier to extend the commander.

Anyway, we do not need it now :D. I will rewrite to the  `minimist` version.

**Comment by vanpipy** [comment]
Hi, @jaywcjlove ,

I turn around again and finish it in the end!! 😆

**Comment by jaywcjlove** [comment]
@vanpipy Thx! Hope to improve the documentation.

**Pull request merged**
